In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

D:\Anaconda\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
D:\Anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)typ

In [2]:
dataset = pd.read_csv('C:/Users/ldmag/Downloads/Churn_Modelling.csv')

In [3]:
dataset.head

<bound method NDFrame.head of       RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfPro

In [4]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [6]:
print(y)

[1 0 1 ... 1 1 0]


In [7]:
## Encoding categorical data
# Gender
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [8]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [9]:
# Geographical OHE
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ot = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ot.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [11]:
# splitting training and test 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)

# scaling features
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
## Building the ANN
from keras.models import Sequential
from keras.layers import Dense

ann = Sequential()
ann.add(Dense(units = 6, activation = 'relu')) #input layer and first hidden layer
ann.add(Dense(units = 6, activation = 'relu')) #second hidden layer
ann.add(Dense(units = 1, activation = 'sigmoid')) #output layer with 1 unit function because Y is binary

# compile ANN
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics= ['accuracy'])

In [13]:
## Training ANN 
ann.fit(X_train, y_train, batch_size = 32, epochs = 150)

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/150
8000/8000 [==============================] - 2s 244us/step - loss: 0.5154 - accuracy: 0.7960
Epoch 2/150
8000/8000 [==============================] - 0s 52us/step - loss: 0.4715 - accuracy: 0.7960
Epoch 3/150
8000/8000 [==============================] - 0s 54us/step - loss: 0.4531 - accuracy: 0.7960
Epoch 4/150
8000/8000 [==============================] - 0s 54us/step - loss: 0.4380 - accuracy: 0.7960
Epoch 5/150
8000/8000 [==============================] - 0s 56us/step - loss: 0.4237 - accuracy: 0.8005
Epoch 6/150
8000/8000 [==============================] - 0s 54us/step - loss: 0.4107 - accuracy: 0.8120
Epoch 7/150
8000/8000 [==============================] - 0s 55us/step - loss: 0.4014 - accuracy: 0.8166
Epoch 8/150
8000/8000 [==============================] - 0s 54us/step - loss: 0.3940 - accuracy: 0.8169
Epoch 9/150
8000/8000 [==============================] - 0s 54us/step - 

8000/8000 [==============================] - 0s 53us/step - loss: 0.3415 - accuracy: 0.8611
Epoch 75/150
8000/8000 [==============================] - 0s 52us/step - loss: 0.3416 - accuracy: 0.8610
Epoch 76/150
8000/8000 [==============================] - 0s 53us/step - loss: 0.3412 - accuracy: 0.8606
Epoch 77/150
8000/8000 [==============================] - 0s 54us/step - loss: 0.3412 - accuracy: 0.8636
Epoch 78/150
8000/8000 [==============================] - 0s 54us/step - loss: 0.3412 - accuracy: 0.8609
Epoch 79/150
8000/8000 [==============================] - 0s 52us/step - loss: 0.3409 - accuracy: 0.8608
Epoch 80/150
8000/8000 [==============================] - 0s 53us/step - loss: 0.3410 - accuracy: 0.8605
Epoch 81/150
8000/8000 [==============================] - 0s 52us/step - loss: 0.3406 - accuracy: 0.8622
Epoch 82/150
8000/8000 [==============================] - 0s 54us/step - loss: 0.3410 - accuracy: 0.8636
Epoch 83/150
8000/8000 [==============================] - 0s 61us/st

## CASE: Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: $ 50000

So, should we say goodbye to that customer?

In [17]:
#any input needs to be a 2d array; use transform method for new observations
#conditional operator states that value over 0.5 is considered as 1 in our conclusion
print(ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

# probability is given as 0.06, so this customer is likely to stay

[[False]]


In [19]:
## Predicting test results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [20]:
## Confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1523   72]
 [ 206  199]]


0.861